# <span style="color:darkblue"> Lecture 7: User-defined Functions </span>

## <span style="color:darkblue"> I. Import Libraries </span>

In [1]:
# the "numPy" library is used for mathematical operations
# the "matplotlib" library is for generating graphs
# the "pandas" library is for manipualting datasets

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## <span style="color:darkblue"> II. Introduction to Functions </span>

<font size="5"> 

A function is ...

- a **block of reusable** code to perform a a specific task
- Functions avoid repetition
- As our code grows larger, functions make it more manageable



<font size="5"> 

"Built-in" functions are those from Python libraries, e.g.

```print()```, ```type()```, ```round()```,```abs()```, ```len()```

- The "arguments" are the values of the inputs
- The "return" is the output


In [2]:
# Argument:   "Hello" 
# Return:     Showing the message on screen

print("Hello")


Hello


In [3]:
# Argument:  3.14
# Return:    The type of object, e.g. int, str, boolean, float, etc.

type(3.14)


float

In [6]:
# First Argument:   np.pi     (a numeric value)
# Second Argument:  6         (the number of decimals)
# Return:  Round the first argument, given the number of decimals in the second argument

round(np.pi,  3)


3.142

In [8]:
# Argument: -4
# Return:   The absolute value
abs(-4)


4

In [11]:
list_fruits = ["Apple","Orange","Pear"]

# Argument: list_fruits
# Return:   The number of elements in the list
len(list_fruits)

3

<font size = "5">

Enter arguments by assigning parameters

In [22]:
# Here "df" and "size" are both parameters
# They get assigned the arguments "2" and "20", respectively
# The return is a vector of random variables, 20 random floats

vec_x = np.random.chisquare(df = 2, size = 20)


In [23]:
vec_x

array([3.90929402, 1.80545975, 4.80311985, 0.32024199, 4.17498853,
       0.10252738, 1.3050455 , 0.35502782, 5.48605128, 1.72655337,
       0.84684503, 3.83850994, 3.23445727, 0.06515734, 0.26990034,
       4.06547478, 6.18580089, 0.2864299 , 5.78629595, 1.22206862])

In [28]:
vec_y = np.random.normal(loc = 2, scale = 5, size = 20)
vec_z = np.random.uniform(low = -2, high =2, size = 50)

In [27]:
vec_y

array([1.02212245, 2.23536733, 1.98192557, 3.21073487, 2.23244805,
       2.52490848, 2.83067129, 3.74378855, 1.68122545, 0.06512808,
       0.01513243, 0.72627283, 1.45822494, 0.06206168, 1.55787285,
       2.72584548, 1.90816385, 2.17787647, 2.39539783, 2.48197556])

In [29]:
vec_z

array([ 8.87946054e-01, -7.66445372e-01, -1.10675636e+00,  1.16837889e+00,
        3.77840822e-01,  1.04557533e+00,  7.90920150e-01, -3.34507215e-01,
        8.22677606e-01,  3.40068840e-01,  5.10250360e-01,  1.01644007e+00,
       -1.82124184e+00, -6.11837555e-01,  8.56575046e-01,  7.05493231e-01,
       -1.21964206e-03,  9.83135546e-01, -1.35725218e-01, -3.20566793e-01,
        2.95726667e-01,  1.26035779e-01, -1.91251140e+00, -1.40644235e+00,
       -5.19890108e-01,  9.90072120e-01, -4.61614246e-01,  3.79204558e-01,
        1.76100880e+00,  1.28801962e+00, -5.86485446e-01, -1.20767913e+00,
       -9.43923656e-01,  1.56577061e+00,  1.60394306e-01,  1.34989935e+00,
        2.31404147e-01, -4.98538046e-01,  1.72518269e+00, -1.99389580e+00,
       -1.77872558e+00,  6.72370455e-01, -1.51835478e+00, -8.80394666e-01,
        1.42477287e+00,  1.36317748e+00,  1.95602782e+00,  3.94063286e-01,
       -1.37194384e+00, -1.36969179e+00])

<font size = "5">

Discussion:

- What are the parameters, arguments, and returns above?


## <span style="color:darkblue"> III. Custom Functions </span>

<font size = "5">

You can write your own functions:

```python

    #---- DEFINE
    def my_function(parameter):
        body
        return expression

    #---- RUN
    my_function(parameter = argument) 

    #---- RUN
    my_function(argument)
```
<br>

<font size = "5">

Example: Calculate

$V=P\left(1+{\frac {r}{n}}\right)^{nt}$




In [31]:
# We are going to define a function "fn_compute_value"
# You can choose any name
# Using prefixes like "fn_" can help you remember this is a "function" object
# What are the parameters?

def fn_V(P,r,n,t):
    V=P*(1+r/n)**n*t
    return V

In [35]:
# You can know compute the formula with different values

#V1 = fn_compute_value(P = 1000, r = 0.01, n = 20, t=10)
#V2 = fn_compute_value(P = 10, r = 0.01, n = 20, t=10)

print(fn_V(P=1000, r=0.01, n=20, t=10))
print(fn_V(P=10, r=0.01, n=20, t=10))

10100.476428032965
101.00476428032965


<font size = "5">

Try it yourself:

- Write a function that calculates $f(x) = x^2 + 2x + 1$.


In [41]:
# Write your own code here
def fn_x(x):
    f=x**2+2*x+1
    return f

fn_x(x=5)

36

<font size = "5">

Try it yourself: Write a function

- with a parameter "numeric_grade"
- Inside the function write an if/else statement for grade $\ge 55$.
- If it's true, then assign "status = pass"
- If it's false, then assign "status = fail"
- Return the value of "status"

In [53]:
# Write your own code
def fn_grade(numeric_grade):
    if numeric_grade>=55:
        status="pass"
    else:
        status="fail"
    return status

fn_grade(55)

'pass'

<font size = "5">

Try it yourself! Write a function 
- Write a function with parameters "first_name", "last_name", "car_model"
- Return a message saying:

"Dear customer {first_name} {last_name}, your car model {car_model} is ready" 





In [1]:
# Write your own code
def fn_message(first_name, last_name, car_model):
    return "Dear customer "+first_name+last_name+" your car model "+car_model+" is ready"

## <span style="color:darkblue"> III. Lambda Functions </span>

<font size = "5">

"Lambda Functions" are defined in one line:

```python
my_function = lambda parameters: expression
```

<font size = "5">

Example: Calculate $x + y + z$

In [55]:
# (a) Define function
fn_sum = lambda x,y,z: x + y + z

# (b) Run function
fn_sum(1,2,3)

6

<font size = "5"> Example: Calculate

$V=P\left(1+{\frac {r}{n}}\right)^{nt}$


In [57]:
fn_compute_value =  lambda P,r,n,t: P*(1 + r/n)**(n*t)

In [58]:
V1 = fn_compute_value(P = 1000, r = 0.01, n = 20, t=10)
V2 = fn_compute_value(P = 10, r = 0.01, n = 20, t=10)

print(V1)
print(V2)


1105.1432983541217
11.051432983541218


<font size = "5">

Try it yourself!

(a) Boleean + Functions

- Write a function called "fn_iseligible_vote"
- This functions returns a boolean value that checks whether age $\ge$ 18

In [64]:
fn_iseligible_vote = lambda age: age>=18

fn_iseligible_vote(20)

True

In [62]:
# Write your own code
def fn_iseligible_vote(age):
    if age>=18:
        return "True"
    else:
        return "False"
    
fn_iseligible_vote(17)

'False'

<font size = "5">

(b) Looping  + Functions

- Create list_ages = [18,29,15,32,6]
- Write a loop that checks whether above ages are eligible to vote
- Use the above function

In [65]:
# Write your own code

list_ages = [18,29,15,32,6]

#for age in list_ages:
#    print("A person with age " + str(age) + " can vote: " +
#           str(fn_iseligible_vote(age)))

result_list=[]
for age in list_ages:
    result_list.append(fn_iseligible_vote(age))

In [67]:
print(result_list)
np.sum(result_list)

[True, True, False, True, False]


3

## <span style="color:darkblue"> IV. (Optional) Functions for visualization </span>

<font size = "5">
Returning a value is not always necesary, you can write:

```python

    #---- DEFINE
    def my_function(parameter):
        body
```

<font size = "5">

Example: A customized plot

- You can use functions to store your favorite aesthetic

In [ ]:
# Define the function
def red_histogram(vec_x,title):
    plt.hist(x = vec_x, color = "red")
    plt.title(title)
    plt.ylabel("Frequency")
    plt.show()

carfeatures = pd.read_csv("data/features.csv")

red_histogram(vec_x = carfeatures["weight"], title = "Histogram")
red_histogram(vec_x = carfeatures["acceleration"], title = "Histogram")


<font size = "5">

Try it yourself!

Create a function that computes a red scatter plot that takes $y$ and $x$ inputs

In [ ]:
# Write your own code

# Define the function
